language: perl
perl:
  # - "5.6" # does not work on Travis anymore?!
  #- "5.8.4"
  #- "5.8.4-thr"
  #- "5.8"         # common, prebuilt version
  #- "5.10"
  #- "5.12"
  #- "5.14"
  #- "5.16"
  #- "5.18"
  #- "5.18.1-thr"
  #- "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
  - "blead"

env:
  - HTTP_PROXY="http://example.com/"
  - HTTP_PROXY=

addons:
  apt:
  homebrew:
    packages:
      - perl
      - perlbrew

os:
  - osx
  - linux

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
  - os: linux
    sudo: false
  - os: osx
  #allow_failures:
  #  - perl: blead
  #  #- perl: 5.6.2

    #addons:
    #  apt:
    #    packages:
    #      - bison

#sudo: false

before_install:
  # Install perlbrew the hard way, on OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade; brew list perl || brew install perl ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade; brew upgrade perl libpng ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then \curl -L http://install.perlbrew.pl | bash; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then source ~/perl5/perlbrew/etc/bashrc; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then export PATH=$HOME/perl5/perlbrew/bin:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then echo $TRAVIS_PERL_VERSION; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then perlbrew install perl-$TRAVIS_PERL_VERSION; perlbrew use perl-$TRAVIS_PERL_VERSION; perlbrew install-cpanm; fi
  #
  # Install local::lib
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L http://cpanmin.us | perl - --notest --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib); fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L http://cpanmin.us | perl - --notest App::cpanminus; fi
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
  - cpan-install ExtUtils::MakeMaker~6.68
  - cpan-install CPAN::Meta
  - cpan-install --deps

script:
  - cd $BUILD_DIR
  - perl Makefile.PL && make
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then prove -blv xt/ t/ ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then prove -j $(test-jobs) -blv $(test-dirs) ; fi

branches:
  except:
    - /^wip\//
    - /^blocked/
#notifications:
#  email: false
#  irc:
#    channels:
#      - "irc.perl.org#moo-smoke"
#    template:
#      - "%{repository}#%{build_number} %{branch} by %{author}: %{message} (%{build_url})"
#    on_success: change
#    on_failure: always
#    skip_join: true
