language: perl
perl:
  #- "5.6.2"       # ancient, not supported
  - "5.8.8"       # common, prebuilt version
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.18.1-thr"
  - "5.20"
  - "5.22"
  - "5.24"
  - dev
matrix:
  allow_failures:
    - perl: blead
sudo: false
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - export SPLIT_BUILD=0
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install ExtUtils::MakeMaker~6.68
  # for building on 5.6.2
  - cpan-install CPAN::Meta
  - cpan-install --deps
script:
  - cd $BUILD_DIR
  - perl Makefile.PL && make
  - prove -blv $(test-dirs)
branches:
  except:
    - /^wip\//
    - /^blocked/
#notifications:
#  email: false
#  irc:
#    channels:
#      - "irc.perl.org#moo-smoke"
#    template:
#      - "%{repository}#%{build_number} %{branch} by %{author}: %{message} (%{build_url})"
#    on_success: change
#    on_failure: always
#    skip_join: true
