---
abstract: 'spawn a local HTTP server for testing'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Find: '0'
  File::Path: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-HTTP-LocalServer
no_index:
  directory:
    - t
    - inc
requires:
  CGI: '0'
  Carp: '0'
  Cwd: '0'
  File::Basename: '0'
  File::Spec: '0'
  File::Temp: '0'
  Getopt::Long: '0'
  HTTP::Daemon: '6.05'
  HTTP::Request::AsCGI: '0'
  HTTP::Response: '0'
  HTTP::Tiny: '0'
  IO::Socket::INET: '0'
  IO::Socket::IP: '0.25'
  Socket: '0'
  Time::HiRes: '0'
  URI: '0'
  URI::URL: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/Corion/Test-HTTP-LocalServer/issues
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/Test-HTTP-LocalServer.git
version: '0.75'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
